import { Partner } from "./partners";

export const PARTNERS: Partner[] = [
    {id: 0,
        number: 'PT-001000',
        salutation: 'Herr',
        titel: '',
        firstName: 'Robby',
        lastName: 'Bleck',
        birthday: new Date(1980, 10, 5),
        street: 'Am Hartenberg',
        houseNumber: '64 b',
        postCode: '56377',
        city: 'Seelbach',
        fon: '02604/45498877',
        mobile: '0166/1770863',
        email: 'rbleck@hoster.none',
    },
    {id: 1,
        number: 'PT-001001',
        salutation: 'Herr',
        titel: '',
        firstName: 'Theobert',
        lastName: 'Lüttmann',
        birthday: new Date(),
        street: 'Hoher Weg',
        houseNumber: '194',
        postCode: '72534',
        city: 'Hayingen',
        fon: '07386/12005971',
        mobile: '0156/9259672',
        email: 't.luettmann@xyz.none',
    },
    {id: 2,
        number: 'PT-001002',
        salutation: 'k.A.',
        titel: 'Dr.',
        firstName: 'Vinzent',
        lastName: 'Werning',
        birthday: new Date(),
        street: 'Von-Oppenheim-Straße',
        houseNumber: '200',
        postCode: '86485',
        city: 'Biberbach',
        fon: '08271/48862505',
        mobile: '0159/2986853',
        email: 'v_werning@quickmail.none',
    },
    {id: 3,
        number: 'PT-001003',
        salutation: 'Frau',
        titel: '',
        firstName: 'Mechthilde',
        lastName: 'Flohr',
        birthday: new Date(),
        street: 'Am Hirsch',
        houseNumber: '141',
        postCode: '34308',
        city: 'Bad Emstal',
        fon: '05624/43037771',
        mobile: '0160/7777766',
        email: 'm1934@mymail.none',
    },
    {id: 4,
        number: 'PT-001004',
        salutation: 'Herr',
        titel: 'Dr.',
        firstName: 'Reginhardt',
        lastName: 'Langhorst',
        birthday: new Date(),
        street: 'Osnabrücker Straße',
        houseNumber: '165',
        postCode: '87660',
        city: 'Irsee',
        fon: '08341/32393656',
        mobile: '0153/2898515',
        email: 'reginhardt-langhorst@company.none',
    },
    {id: 5,
        number: 'PT-001005',
        salutation: 'Herr',
        titel: 'Dr.',
        firstName: 'Sigwart',
        lastName: 'Schwank',
        birthday: new Date(),
        street: 'Im Weiher',
        houseNumber: '183',
        postCode: '58454',
        city: 'Witten',
        fon: '02302/39804599',
        mobile: '0151/1421104',
        email: 'sigwart1961@validmail.none',
    },
    {id: 6,
        number: 'PT-001006',
        salutation: 'Frau',
        titel: 'Dr.',
        firstName: 'Ehrentrud',
        lastName: 'Schwarzenberg',
        birthday: new Date(),
        street: 'Auf Heinzenbuchen',
        houseNumber: '9',
        postCode: '67735',
        city: 'Mehlbach',
        fon: '06301/71509873',
        mobile: '0161/7332123',
        email: 'ehrentrud_schwarzenberg@bestmail.none',
    },
    {id: 7,
        number: 'PT-001007',
        salutation: 'Herr',
        titel: '',
        firstName: 'Emeram',
        lastName: 'Eickmeier',
        birthday: new Date(),
        street: 'Wolfshovener Straße',
        houseNumber: '188',
        postCode: '76189',
        city: 'Karlsruhe',
        fon: '0721/14985354',
        mobile: '0179/3570755',
        email: 'emeram_eickmeier@email.none',
    },
    {id: 8,
        number: 'PT-001008',
        salutation: 'Frau',
        titel: '',
        firstName: 'Mariechen',
        lastName: 'Klemm',
        birthday: new Date(),
        street: 'Südlager',
        houseNumber: '9 a',
        postCode: '21379',
        city: 'Lüdersburg',
        fon: '04136/64700811',
        mobile: '0165/4476284',
        email: 'mariechen_klemm@retromail.none',
    },
    {id: 9,
        number: 'PT-001009',
        salutation: 'Herr',
        titel: '',
        firstName: 'Bartold',
        lastName: 'Abt',
        birthday: new Date(),
        street: 'Bedburger Straße',
        houseNumber: '71',
        postCode: '86676',
        city: 'Ehekirchen',
        fon: '08435/23932908',
        mobile: '0163/4885631',
        email: 'bartoldabt@inter-mail.none',
    },
    {id: 10,
        number: 'PT-001010',
        salutation: 'Herr',
        titel: 'Prof.',
        firstName: 'Thomas',
        lastName: 'Schneeweiß',
        birthday: new Date(),
        street: 'Balder Straße',
        houseNumber: '100',
        postCode: '58809',
        city: 'Neuenrade',
        fon: '02392/69688144',
        mobile: '0159/9068022',
        email: 'tschneeweiss@company.none',
    },
    {id: 11,
        number: 'PT-001011',
        salutation: 'Frau',
        titel: 'Prof. Dr.',
        firstName: 'Susanne',
        lastName: 'Caliskan',
        birthday: new Date(),
        street: 'Piusallee',
        houseNumber: '104',
        postCode: '25899',
        city: 'Galmsbüll',
        fon: '04661/90304882',
        mobile: '0177/2274740',
        email: 'susannecaliskan@goggle-mail.none',
    },
    {id: 12,
        number: 'PT-001012',
        salutation: 'Herr',
        titel: '',
        firstName: 'Laurenz',
        lastName: 'Keiser',
        birthday: new Date(),
        street: 'Feuerbachstraße',
        houseNumber: '64',
        postCode: '72793',
        city: 'Pfullingen',
        fon: '07121/33700841',
        mobile: '0164/3377801',
        email: 'laurenz.keiser@mymail.none',
    },
    {id: 13,
        number: 'PT-001013',
        salutation: 'Herr',
        titel: 'Dr. Dr.',
        firstName: 'Alfred',
        lastName: 'Kratz',
        birthday: new Date(),
        street: 'Am Hartenberg',
        houseNumber: '195c',
        postCode: '56072',
        city: 'Koblenz am Rhein',
        fon: '0261/1037464',
        mobile: '0157/9589069',
        email: 'akratz@open-mail.none',
    },
    {id: 14,
        number: 'PT-001014',
        salutation: 'Frau',
        titel: '',
        firstName: 'Berna',
        lastName: 'Schettler',
        birthday: new Date(),
        street: 'Paulstraße',
        houseNumber: '70',
        postCode: '83109',
        city: 'Großkarolinenfeld',
        fon: '08031/36692653',
        mobile: '0166/3839161',
        email: 'b_schettler@trashmail.none',
    },
];
